- CHANGELOG.md
- app/policies/backoffice/service_policy.rb
- app/services/service/destroy.rb
- app/views/backoffice/services/show.html.haml
- spec/policies/backoffice/service_policy_spec.rb
- spec/requests/backoffice/services_spec.rb
- spec/services/service/destroy_spec.rb
Add delete button
in the service backoffice view
Closes #5
> feat:[#5] Add delete action for services

- .github/workflows/ci_backend.yml
- .github/workflows/ci_frontend_manager.yml
- .github/workflows/ci_frontend_user.yml
- .github/workflows/e2e.yml
- CHANGELOG.md
- README.md
- app/components/presentable/description_component.html.haml
- app/components/presentable/details_component.html.haml
- app/controllers/user_action_controller.rb
- app/helpers/service_helper.rb
- app/services/probes/create.rb
- app/views/services/guidelines/index.html.haml
- app/views/services/index.html.haml
- app/views/services/opinions/index.html.haml
- config/application.rb
- config/locales/simple_form.en.yml
- config/locales/views/components/en.yml
- spec/features/backoffice/services_spec.rb
- spec/features/recommended_spec.rb
- spec/features/service_recommendations_spec.rb
- test/system/cypress/support/resources.ts
> remove suggested services, hide recommendations

- app/models/filter.rb
- app/models/service/search.rb
- app/views/services/filters/_wrapper.html.haml
- db/schema.rb
- spec/features/filter_spec.rb
- test/system/cypress/e2e/regression_tests/backoffice/scientific-domain/scientific-domain.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/all_filters.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/dedicated_for.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/infrastructutes_platforms.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/order_type.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/providers.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/rating.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/resource_availability.spec.ts
- test/system/cypress/e2e/regression_tests/service-page/filters/scientific_domains.spec.ts
> fix:[#HOTFIX] Collapse all filters by default

- app/views/backoffice/services/bundles/_form.html.haml
> add styling to delete bundle button

- CHANGELOG.md
- app/controllers/backoffice/catalogues_controller.rb
> fill admin fields in catalogue creation form

- .github/workflows/ci_backend.yml
- .github/workflows/ci_frontend_manager.yml
- .github/workflows/ci_frontend_user.yml
- .github/workflows/e2e.yml
- CHANGELOG.md
- app/models/offer.rb
https://github.com/cyfronet-fid/marketplace/issues/3263
> fix offer access type validator

- CHANGELOG.md
- app/models/bundle.rb
- app/services/bundle/draft.rb
- app/services/bundle/update.rb
- app/services/service/application_service.rb
- app/services/service/suspend.rb
- app/services/service/unpublish.rb
- spec/services/bundle/update_spec.rb
- spec/services/offer/destroy_spec.rb
- spec/services/offer/unpublish_spec.rb
- spec/services/offer/update_spec.rb
- spec/services/service/unpublish_spec.rb
- spec/services/service/update_spec.rb
https://pr-69.docker-fid.grid.cyf-kr.edu.pl
> draft bundle if offer not publish

- CHANGELOG.md
- app/components/presentable/header_component.html.haml
- app/helpers/search_links_helper.rb
- app/views/components/presentable/header_component/_categorization.html.haml
- app/views/services/_service_details.html.haml
> organisation name links to provider detail page

- CHANGELOG.md
- app/views/layouts/backoffice/_navbar.html.haml
> hide other settings tab for non-superuser

- CHANGELOG.md
- docker-compose-x64.yml
- docker-compose.yml
- docs/upgrade/3.58.0.md
Instructions how to update db on local machines
are included in docs/upgrade/3.58.0.md
> chore:[] Update postgres from 14.1 to 16.4

- app/policies/backoffice/orderable_policy.rb
Fix policy method for displaying `Publish`
action in offers. Add persistence check
Closes #95
> fix:[#95] Fix adding a new offer

- app/views/backoffice/catalogues/_form.html.haml
- app/views/backoffice/other_settings/categories/_form.html.haml
- app/views/backoffice/other_settings/platforms/_form.html.haml
- app/views/backoffice/other_settings/scientific_domains/_form.html.haml
- app/views/backoffice/other_settings/vocabularies/_form.html.haml
- app/views/backoffice/providers/_form.html.haml
> fix back to previous button behaviour

- CHANGELOG.md
- app/models/parameter/constant.rb
- app/views/parameters/template/_attribute.html.haml
- spec/serializers/api/v1/offer_serializer_spec.rb
Add unit field to the schema and form
of the constant parameter
Closes #101
> feat:[#101] Add unit to the constant parameter

- CHANGELOG.md
- app/helpers/order_nav_helper.rb
- app/views/layouts/order.html.haml
Fix redirect to login when
user is trying to order a service
Closes #3337
> fix:[#3337] Fix login in ordering

- CHANGELOG.md
- app/models/catalogue.rb
- app/models/service.rb
- db/data.yml
> shorten dev data

- app/assets/stylesheets/_bootstrap-customizations.scss
- app/views/admin/features/show.html.haml
- app/views/admin/helps/_item.html.haml
- app/views/admin/helps/_section.html.haml
- app/views/admin/helps/_toc.html.haml
- app/views/admin/helps/show.html.haml
- app/views/admin/leads/_item.html.haml
- app/views/admin/leads/_section.html.haml
- app/views/admin/leads/index.html.haml
- app/views/admin/tour_feedbacks/index.html.haml
- app/views/layouts/_sections.html.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/admin/_navbar.html.haml
- app/views/leads/learn_more/_card.html.haml
- app/views/leads/use_case/_card.html.haml
- config/breadcrumbs/admin.rb
- spec/features/admin/help_builder_spec.rb
Closes: #23 
Added admin panel first template mods
Added Lead creator new view:
> 23 new admin panel

- .github/workflows/ci_backend.yml
- .github/workflows/ci_frontend_manager.yml
- .github/workflows/ci_frontend_user.yml
- .github/workflows/e2e.yml
- CHANGELOG.md
- app/assets/stylesheets/_bootstrap-customizations.scss
- app/assets/stylesheets/_variables.scss
- app/controllers/backoffice/services/offers_controller.rb
- app/helpers/backoffice/offers_helper.rb
- app/inputs/custom_input.rb
- app/javascript/controllers/duplicate_controller.js
- app/javascript/controllers/exit_controller.js
- app/javascript/controllers/index.js
- app/models/attribute.rb
- app/models/offer.rb
- app/models/offer/parameters.rb
- app/policies/backoffice/offer_policy.rb
- app/services/offer/create_as_draft.rb
- app/services/offer/update_as_draft.rb
- app/views/backoffice/services/offers/_duplicate_modal.html.haml
- app/views/backoffice/services/offers/_exit_modal.html.haml
- app/views/backoffice/services/offers/_form.html.haml
- app/views/backoffice/services/offers/steps/_description.html.haml
- app/views/layouts/common_parts/services/_offer.html.haml
- app/views/layouts/common_parts/services/_offers.html.haml
- app/views/services/_offer.html.haml
- config/routes.rb
- spec/models/attribute/quantity_price_spec.rb
- spec/models/attribute_spec.rb
> 121 118 create as draft and duplicate

- CHANGELOG.md
- README.md
Added readme section about manual development setup
> chore: update readme about manual dev setup

- CHANGELOG.md
- config/eosc_explore_banner.yml
Change default link to
`https://explore.sandbox.eosc-beyond.eu/`
Closes #3391
> fix:[#3391] Change default link to the explore

- app/assets/stylesheets/_bootstrap-customizations.scss
- app/views/layouts/navbar/_navbar_tabs.html.haml
- app/views/layouts/navbar/_provider_panel.html.haml
closes: #146 
mods of dropdown menu done due to the list:
Backoffice link was working properly. Maybe a lack of permissions? Please add some more informations about error.
> style: [#146] navbar dropdown mods

- app/services/jms/publish.rb
- bin/jms-subscriber
- config/stomp_publisher.yml
- config/stomp_subscriber.yml
- lib/config_loader_helper.rb
- lib/jms/subscriber.rb
- spec/models/publishable.rb
Extend JMS configuration
to run multiple clients
Closes #215
> feat:[#215] Subscription on multiple Catalogues
